##1/7/17

##Format CLEAR III data set for applying our method

##Construct a data frame entitled "data" with variables:
##subject id, treatment assignment, 
##30-day mRS, 180-day mRS, 30-day mortality, and 180-day mortality.
##Missing data are indicated by N/A.

##NOTE: The data sets used and generated by this script are not included.
####### This is because the CLEAR III data set is proprietary.

###################################################################################
##Load csv files##
###################################################################################
setwd("/users/emhuang/data/CLEARIII")

rm(list=ls())

outcome_tmt <- read.csv(file ="CLEARIII_mRS outcomes and treatment_20160115.csv")


###################################################################################
##Put together data set##
###################################################################################

##Step 1: Formatting patient id, outcomes, and treatment assignment##
head(outcome_tmt)

table(outcome_tmt$died, outcome_tmt$patient_status, useNA = "ifany")
table(outcome_tmt$lost_to_followup, outcome_tmt$patient_status, useNA = "ifany")
table(outcome_tmt$lost_to_followup, outcome_tmt$glasgow_rankin, useNA = "ifany")
table(outcome_tmt$rankin_not_done, outcome_tmt$glasgow_rankin, useNA = "ifany")
table(outcome_tmt$rankin_not_done, outcome_tmt$site_rankin, useNA = "ifany")

##Define variable mortality with Alive = 0 and Dead = 1 and Lost to follow-up = NA
outcome_tmt$mortality <- (outcome_tmt$patient_status=="Dead")
outcome_tmt$mortality[outcome_tmt$patient_status == "Lost to follow-up"] <- NA

##Relabel treatment assignment to 0 and 1
outcome_tmt$tmt <- 1
outcome_tmt$tmt[outcome_tmt$treatment == "A"] <- 0


outcome_tmt <- data.frame(patientnum = outcome_tmt$patientnum,
                          visit_day = outcome_tmt$visit_day,
                          mortality = outcome_tmt$mortality,
                          rankin = outcome_tmt$glasgow_rankin,
                          tmt = outcome_tmt$tmt)

##For those who died, rankin = 6 
##For some, we know neither mortality nor rankin
##For some, we know they are alive but rankin is unknown
table(outcome_tmt$mortality, outcome_tmt$rankin, useNA = "ifany")

sub30 <- subset(outcome_tmt, visit_day == 30)
sub180 <- subset(outcome_tmt, visit_day == 180)

##Rename outcome variables in sub30 and sub180 
names(sub30)[3:4] <- c("mortality30","rankin30")
names(sub180)[3:4] <- c("mortality180","rankin180")

##Do not need visit_day anymore and only need tmt in one of sub30 and sub180
sub30 <- sub30[,-c(2,5)]
sub180 <- sub180[,-2]

data <- merge(sub30, sub180, by = "patientnum")

##Step 2: Save data
setwd("/users/emhuang/CIpropBenefit/CLEARIII/constructDataset")
save(data, file= "data.Rdata")

##Step 3: Put together .txt files that will be used to apply our method
##There will be a .txt file per outcome
##Each .txt file will have a row vector with the elements:
##number of participants assigned to control
##number of participants assigned to treatment
##number of participants assigned to control and with outcome = 1
##....
##number of participants assigned to control and with outcome = L
##number of participants assigned to treatment and with outcome = 1
##....
##number of participants assigned to treatment and with outcome = L

##Create .txt file for mortality30
temp <- subset(data, !is.na(mortality30))
val <- c(sum(temp$tmt == 0), sum(temp$tmt == 1),
         sum(temp$tmt == 0 & temp$mortality30 == 1), sum(temp$tmt == 0 & temp$mortality30 == 0),
         sum(temp$tmt == 1 & temp$mortality30 == 1), sum(temp$tmt == 1 & temp$mortality30 == 0))
write.table(val, file = "mortality30.txt", row.names = FALSE, col.names = FALSE)

##Create .txt file for mortality180
temp <- subset(data, !is.na(mortality180))
val <- c(sum(temp$tmt == 0), sum(temp$tmt == 1),
         sum(temp$tmt == 0 & temp$mortality180 == 1), sum(temp$tmt == 0 & temp$mortality180 == 0),
         sum(temp$tmt == 1 & temp$mortality180 == 1), sum(temp$tmt == 1 & temp$mortality180 == 0))
write.table(val, file = "mortality180.txt", row.names = FALSE, col.names = FALSE)

##Create .txt file for rankin30
temp <- subset(data, !is.na(rankin30))
val <- c(sum(temp$tmt == 0), sum(temp$tmt == 1),
         sum(temp$tmt == 0 & temp$rankin30 == 6),
         sum(temp$tmt == 0 & temp$rankin30 == 5),
         sum(temp$tmt == 0 & temp$rankin30 == 4),
         sum(temp$tmt == 0 & temp$rankin30 == 3),
         sum(temp$tmt == 0 & temp$rankin30 == 2),
         sum(temp$tmt == 0 & temp$rankin30 == 1),
         sum(temp$tmt == 0 & temp$rankin30 == 0),
         sum(temp$tmt == 1 & temp$rankin30 == 6),
         sum(temp$tmt == 1 & temp$rankin30 == 5),
         sum(temp$tmt == 1 & temp$rankin30 == 4),
         sum(temp$tmt == 1 & temp$rankin30 == 3),
         sum(temp$tmt == 1 & temp$rankin30 == 2),
         sum(temp$tmt == 1 & temp$rankin30 == 1),
         sum(temp$tmt == 1 & temp$rankin30 == 0))
write.table(val, file = "rankin30.txt", row.names = FALSE, col.names = FALSE)

##Create .txt file for rankin180
temp <- subset(data, !is.na(rankin180))
val <- c(sum(temp$tmt == 0), sum(temp$tmt == 1),
         sum(temp$tmt == 0 & temp$rankin180 == 6),
         sum(temp$tmt == 0 & temp$rankin180 == 5),
         sum(temp$tmt == 0 & temp$rankin180 == 4),
         sum(temp$tmt == 0 & temp$rankin180 == 3),
         sum(temp$tmt == 0 & temp$rankin180 == 2),
         sum(temp$tmt == 0 & temp$rankin180 == 1),
         sum(temp$tmt == 0 & temp$rankin180 == 0),
         sum(temp$tmt == 1 & temp$rankin180 == 6),
         sum(temp$tmt == 1 & temp$rankin180 == 5),
         sum(temp$tmt == 1 & temp$rankin180 == 4),
         sum(temp$tmt == 1 & temp$rankin180 == 3),
         sum(temp$tmt == 1 & temp$rankin180 == 2),
         sum(temp$tmt == 1 & temp$rankin180 == 1),
         sum(temp$tmt == 1 & temp$rankin180 == 0))
write.table(val, file = "rankin180.txt", row.names = FALSE, col.names = FALSE)
